const spots = [
  ['해운대 해수욕장','해운대구 · 해운대해변로','paddle',35.1587,129.1604,'96%','파도 0.5m','바람 3m/s','수온 23°','보통이에요','렌탈샵 12곳'],
  ['송정 해수욕장','해운대구 · 송정동','surf',35.1788,129.1996,'98%','파도 0.8m','바람 5m/s','수온 23°','여유로워요','렌탈샵 3곳'],
  ['광안리 해수욕장','수영구 · 광안해변로','paddle',35.1532,129.1188,'94%','파도 0.4m','바람 3m/s','수온 24°','보통이에요','렌탈샵 5곳'],
  ['다대포 해수욕장','사하구 · 다대동','kayak',35.0464,128.9658,'91%','파도 0.6m','바람 4m/s','수온 22°','여유로워요','렌탈샵 2곳'],
  ['일광 해수욕장','기장군 · 일광읍','kayak',35.2645,129.2336,'90%','파도 0.4m','바람 3m/s','수온 22°','한적해요','렌탈샵 2곳'],
  ['임랑 해수욕장','기장군 · 장안읍','surf',35.3200,129.2670,'88%','파도 0.7m','바람 5m/s','수온 22°','한적해요','렌탈샵 1곳'],
  ['송도 해수욕장','서구 · 송도해변로','paddle',35.0750,129.0170,'86%','파도 0.3m','바람 3m/s','수온 23°','보통이에요','렌탈샵 4곳'],
  ['대변항 해안','기장군 · 기장읍','kayak',35.2240,129.2240,'84%','파도 0.3m','바람 2m/s','수온 22°','한적해요','대여점 1곳'],
  ['오륙도 해맞이공원','남구 · 오륙도로','kayak',35.1000,129.1230,'82%','파도 0.5m','바람 4m/s','수온 23°','확인 필요','편의시설 2곳'],
  ['태종대 감지해변','영도구 · 태종대','kayak',35.0540,129.0870,'80%','파도 0.6m','바람 4m/s','수온 22°','한적해요','대여점 1곳'],
  ['기장 연화리','기장군 · 연화리','paddle',35.2250,129.2440,'79%','파도 0.3m','바람 3m/s','수온 22°','한적해요','대여점 1곳'],
  ['청사포 해변','해운대구 · 청사포','surf',35.1590,129.2000,'78%','파도 0.5m','바람 4m/s','수온 23°','한적해요','렌탈샵 1곳'],
  ['신호 해수욕장','강서구 · 신호동','paddle',35.0800,128.8800,'77%','파도 0.3m','바람 3m/s','수온 23°','한적해요','편의시설 2곳'],
  ['몰운대 해안','사하구 · 몰운대','kayak',35.0480,128.9665,'76%','파도 0.5m','바람 4m/s','수온 22°','확인 필요','대여점 1곳'],
  ['가덕도 대항항','강서구 · 가덕도','kayak',34.9950,128.8110,'75%','파도 0.4m','바람 3m/s','수온 22°','한적해요','대여점 1곳'],
  ['공수마을 해안','기장군 · 공수마을','paddle',35.1900,129.2200,'74%','파도 0.3m','바람 2m/s','수온 22°','한적해요','편의시설 1곳'],
  ['해동용궁사 해안','기장군 · 시랑리','kayak',35.1880,129.2230,'73%','파도 0.4m','바람 3m/s','수온 22°','보통이에요','편의시설 3곳'],
  ['칠암 해안','기장군 · 일광면','surf',35.2750,129.2650,'71%','파도 0.6m','바람 4m/s','수온 22°','한적해요','대여점 1곳']
].map((item,index)=>({name:item[0],location:`부산 ${item[1]}`,activity:item[2],lat:item[3],lng:item[4],score:item[5],wave:item[6],wind:item[7],water:item[8],crowd:item[9],rental:item[10],rating:(4.9-index*.04).toFixed(1),views:1540-index*83+(index%3)*47,baseDistance:Math.max(.8,Math.round((Math.abs(35.16-item[3])*95+Math.abs(129.14-item[4])*70)*10)/10),query:`${item[0]} 부산`,visual:index%3===0?'visual-songjeong':index%3===1?'visual-gwangalli':'visual-dadaepo'}))
const fallbackImages=['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82','https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=900&q=82','https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=900&q=82','https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=82'];
const grid=document.querySelector('#recommendationGrid'),toast=document.querySelector('#toast'),pageView=document.querySelector('#pageView'),detailView=document.querySelector('#detailView'),profileView=document.querySelector('#profileView'),moreButton=document.querySelector('#moreSpotsButton');
const maps=[],markers=[],infos=[];let sortMode='match',showAll=false,detailMap=null,pageMap=null;const getImage=spot=>spot.image||fallbackImages[spots.indexOf(spot)%fallbackImages.length];const favorites=()=>JSON.parse(localStorage.getItem('seaPickFavorites')||'[]');
function toastMessage(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.seaToast);window.seaToast=setTimeout(()=>toast.classList.remove('show'),2400)}
function distanceFor(spot){const region=localStorage.getItem('seaPickRegion')||'';const close=spot.location.includes(region)&&region&&region!=='부산 전체';return close?Math.max(.4,spot.baseDistance/3):spot.baseDistance}
function sorted(items){return [...items].sort((a,b)=>sortMode==='distance'?distanceFor(a)-distanceFor(b):sortMode==='views'?b.views-a.views:Number(b.score.replace('%',''))-Number(a.score.replace('%','')))}
function cardHtml(spot,index,compact=false){return `<article class="spot-card${compact?' saved-card':''}" data-spot="${spot.name}"><div class="spot-visual ${spot.visual}" data-image-for="${spot.name}" style="background-image:url('${getImage(spot)}')"><span class="rank">${String(index+1).padStart(2,'0')} PICK</span><button class="favorite" aria-label="${spot.name} 찜하기" data-favorite="${spot.name}">${favorites().includes(spot.name)?'♥':'♡'}</button></div><div class="spot-info"><div class="spot-title-row"><h3>${spot.name}</h3><span class="rating">★ ${spot.rating}</span></div><p class="spot-location">${spot.location}</p><div class="condition-row"><span class="condition">${spot.wave}</span><span class="condition">${spot.wind}</span><span class="condition">${spot.water}</span></div><div class="spot-footer"><span>${spot.crowd} · ${spot.rental}</span><strong>적합도 ${spot.score}</strong></div></div></article>`}
function render(activity='all',query=''){const key=query.toLowerCase();const filtered=sorted(spots.filter(s=>(activity==='all'||s.activity===activity)&&(!key||`${s.name} ${s.location}`.toLowerCase().includes(key))));const visible=showAll?filtered:filtered.slice(0,6);grid.innerHTML=visible.length?visible.map((s,i)=>cardHtml(s,i)).join(''):`<div class="empty-state">검색 결과가 없어요. 다른 지역이나 해변을 찾아보세요.</div>`;moreButton.hidden=filtered.length<=6||showAll;moreButton.textContent=`부산 해수욕장 더보기 (${Math.max(0,filtered.length-6)}곳) ＋`;bindCards();updateMarkers(filtered)}
function bindCards(){grid.querySelectorAll('[data-spot]').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('button'))return;openDetail(spots.find(s=>s.name===card.dataset.spot))}));grid.querySelectorAll('[data-favorite]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();const name=button.dataset.favorite;const saved=favorites();const next=saved.includes(name)?saved.filter(v=>v!==name):[...saved,name];localStorage.setItem('seaPickFavorites',JSON.stringify(next));button.textContent=next.includes(name)?'♥':'♡';button.style.color=next.includes(name)?'#f48e68':'';toastMessage(next.includes(name)?`${name}을(를) 찜했어요.`:`${name}을(를) 찜 목록에서 삭제했어요.`)}))}
function initMap(){const center={lat:35.16,lng:129.14};['googleMapMini','googleMapLarge'].forEach((id,i)=>{const node=document.querySelector(`#${id}`);if(node){const map=new google.maps.Map(node,{center,zoom:i?11:10,mapTypeControl:true,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy'});maps.push(map);node.parentElement.classList.add('google-maps-ready')}});updateMarkers(spots);loadPlacePhotos()}
function updateMarkers(items){markers.forEach(m=>m.setMap(null));markers.length=0;infos.forEach(i=>i.close());infos.length=0;if(!maps.length)return;items.forEach(spot=>maps.forEach(map=>{const marker=new google.maps.Marker({map,position:{lat:spot.lat,lng:spot.lng},title:spot.name});const info=new google.maps.InfoWindow({content:`<div class="map-info-window"><img src="${getImage(spot)}" alt="${spot.name}"><div><strong>${spot.name}</strong><span>${spot.location}</span><div class="map-info-stats"><b>${spot.water}</b><b>${spot.wind}</b><b>${spot.wave}</b></div><small>${spot.crowd} · ${spot.rental}</small></div></div>`});marker.addListener('click',()=>{info.open({map,anchor:marker});map.panTo({lat:spot.lat,lng:spot.lng});map.setZoom(14);toastMessage(`${spot.name}의 바다 정보를 확인하세요.`)});markers.push(marker);infos.push(info)}))}
async function loadPlacePhotos(){try{const {Place}=await google.maps.importLibrary('places');for(const spot of spots){try{const result=await Place.searchByText({textQuery:`${spot.name}, 부산`,fields:['displayName','photos','location'],language:'ko',region:'KR',maxResultCount:1});const photo=result.places?.[0]?.photos?.[0];if(photo){spot.image=photo.getURI({maxWidth:900,maxHeight:500});document.querySelectorAll(`[data-image-for="${spot.name}"]`).forEach(n=>n.style.backgroundImage=`url('${spot.image}')`)}}catch(e){}}}catch(e){}}
function loadMaps(){if(!window.GOOGLE_MAPS_API_KEY)return;const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(window.GOOGLE_MAPS_API_KEY)}&libraries=places&callback=initGoogleMap`;script.async=true;script.defer=true;document.head.appendChild(script)}window.initGoogleMap=initMap;
function runSearch(){const q=document.querySelector('#searchInput').value.trim();showAll=false;render(document.querySelector('.activity-tab.active').dataset.activity,q);if(q)toastMessage(`'${q}' 위치를 찾았어요.`)}
function openDetail(spot){detailView.innerHTML=`<button class="detail-back" id="detailBack" type="button">← 추천 목록으로 돌아가기</button><div class="detail-hero"><div class="detail-photo" style="background-image:url('${getImage(spot)}')"></div><div class="detail-copy"><p class="eyebrow">SEA PICK DETAIL</p><h2>${spot.name}</h2><p class="detail-location">⌖ ${spot.location}</p><div class="detail-score"><strong>${spot.score}</strong><span>오늘의 활동 적합도<br>현재 컨디션 기준</span></div><div class="detail-stats"><div class="detail-stat"><span>수온</span><strong>${spot.water}</strong></div><div class="detail-stat"><span>풍속</span><strong>${spot.wind}</strong></div><div class="detail-stat"><span>파도</span><strong>${spot.wave}</strong></div></div></div></div><div class="detail-grid"><div class="detail-map-card"><h3>해수욕장 위치</h3><div class="detail-map" id="detailMap"></div></div><div class="detail-info-card"><h3>현장 정보</h3><ul class="detail-list"><li><span>혼잡도</span><strong>${spot.crowd}</strong></li><li><span>장비·편의시설</span><strong>${spot.rental}</strong></li><li><span>조회수</span><strong>${spot.views.toLocaleString()}회</strong></li><li><span>평점</span><strong>★ ${spot.rating}</strong></li></ul><div class="detail-note">출발 전 기상 특보와 장비 상태를 확인하고, 해가 지기 전에 물에서 나와 주세요.</div></div></div>`;document.body.classList.add('detail-active');detailView.hidden=false;history.pushState({detail:spot.name},'',`#place=${encodeURIComponent(spot.name)}`);document.querySelector('#detailBack').onclick=()=>history.back();if(window.google?.maps)setTimeout(()=>{detailMap=new google.maps.Map(document.querySelector('#detailMap'),{center:{lat:spot.lat,lng:spot.lng},zoom:14,streetViewControl:false});new google.maps.Marker({map:detailMap,position:{lat:spot.lat,lng:spot.lng},title:spot.name})},100)}
function openPage(page){document.body.classList.add('page-active');pageView.hidden=false;if(page==='map'){pageView.innerHTML='<button class="detail-back" id="pageBack" type="button">← 홈으로 돌아가기</button><div class="page-heading"><p class="eyebrow">ALL BEACHES MAP</p><h2>부산 해수욕장 지도</h2><p>마커를 눌러 해수욕장 정보를 확인하세요.</p></div><div class="full-page-map" id="googleMapPage"></div>';setTimeout(()=>{if(window.google?.maps){pageMap=new google.maps.Map(document.querySelector('#googleMapPage'),{center:{lat:35.16,lng:129.14},zoom:10,fullscreenControl:true});maps.push(pageMap);updateMarkers(spots)}},100)}else{const saved=spots.filter(s=>favorites().includes(s.name));pageView.innerHTML='<button class="detail-back" id="pageBack" type="button">← 홈으로 돌아가기</button><div class="page-heading"><p class="eyebrow">SAVED BEACHES</p><h2>찜한 장소</h2><p>다시 보고 싶은 해수욕장을 모아두었어요.</p></div>'+(saved.length?`<div class="saved-grid">${saved.map((s,i)=>cardHtml(s,i,true)).join('')}</div>`:'<div class="saved-empty"><span>♡</span><h3>아직 찜한 장소가 없어요.</h3><p>추천 카드의 하트를 눌러 마음에 드는 바다를 저장해 보세요.</p></div>');pageView.querySelectorAll('.saved-card').forEach(card=>card.addEventListener('click',e=>{if(!e.target.closest('button'))openDetail(spots.find(s=>s.name===card.dataset.spot))}))}history.pushState({page},'',`#${page==='map'?'map-page':'saved-page'}`);document.querySelector('#pageBack').onclick=()=>history.back()}
function closeViews(){document.body.classList.remove('detail-active','page-active','profile-active');detailView.hidden=true;pageView.hidden=true;profileView.hidden=true}
function openProfile(){profileView.hidden=false;document.body.classList.add('profile-active');const name=localStorage.getItem('seaPickName')||'민지';document.querySelector('#profileNameInput').value=name;document.querySelector('#regionInput').value=localStorage.getItem('seaPickRegion')||'';document.querySelector('#ageInput').value=localStorage.getItem('seaPickAge')||'';document.querySelector('#genderInput').value=localStorage.getItem('seaPickGender')||'';const chosen=JSON.parse(localStorage.getItem('seaPickActivities')||'[]');document.querySelectorAll('.preference-options input').forEach(i=>i.checked=chosen.includes(i.value));history.pushState({profile:true},'',`${location.pathname}${location.search}#profile`)}
document.querySelectorAll('.activity-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.activity-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');showAll=false;render(tab.dataset.activity,document.querySelector('#searchInput').value.trim())});document.querySelector('#searchButton').onclick=runSearch;document.querySelector('#searchInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();runSearch()}};moreButton.onclick=()=>{showAll=true;render(document.querySelector('.activity-tab.active').dataset.activity,document.querySelector('#searchInput').value.trim())};document.querySelector('#profileButton').onclick=openProfile;document.querySelector('#navMap').onclick=e=>{e.preventDefault();openPage('map')};document.querySelector('#navSaved').onclick=e=>{e.preventDefault();openPage('saved')};document.querySelectorAll('.sort-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sort-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');sortMode=b.dataset.sort;showAll=false;render(document.querySelector('.activity-tab.active').dataset.activity,document.querySelector('#searchInput').value.trim())});document.querySelector('#profileBack').onclick=()=>history.back();document.querySelector('#saveProfile').onclick=()=>{const name=document.querySelector('#profileNameInput').value.trim()||'민지';const region=document.querySelector('#regionInput').value;localStorage.setItem('seaPickName',name);localStorage.setItem('seaPickRegion',region);localStorage.setItem('seaPickAge',document.querySelector('#ageInput').value);localStorage.setItem('seaPickGender',document.querySelector('#genderInput').value);localStorage.setItem('seaPickActivities',JSON.stringify([...document.querySelectorAll('.preference-options input:checked')].map(i=>i.value)));document.querySelector('#visitorName').textContent=name;document.querySelector('#profileName').textContent=name;history.back();document.querySelector('#searchInput').value=region&&region!=='부산 전체'?region:'';render(document.querySelector('.activity-tab.active').dataset.activity,document.querySelector('#searchInput').value);toastMessage(`${name}님 프로필을 저장했어요.`)};window.onpopstate=()=>{closeViews()};
render();loadMaps();
